### ISSUE TITLE
USER STORY : Set up Local Environment MS1

### ISSUE THREAD

**Issue by hennasingh** [hennasingh/ArtisanAlley#1]
### **User Story**

As a developer, I want to set up local environment so that I can create project structure

### **Priority**
[ x ] High
[  ] Medium
[  ] Low

### **Tasks**

- [x]  Add the repository workspace to Gitpod
- [x]  Install Django via npm
- [x]  Create a new project ArtisanAlley
- [x]  Create first app and add to project settings
