### ISSUE TITLE
USER STORY : Install and Setup Postgres Database MS1

### ISSUE THREAD

**Issue by hennasingh** [hennasingh/ArtisanAlley#2]
### **User Story**

As a developer, I want to connect the database so I can store and retrieve user data successfully.

### **Priority**
 [ X ] High
[ ] Medium
 [ ] Low

### **Tasks**
- [x] Get Database URL from Code Institute
- [x] Create env.py file, store database url in the file and add file to .gitignore
- [x]  Install packages (dj-database-url, psycopg2) to connect to Postgres database
- [x] Configure database settings in django project
- [x] Run migrations to create tables for existing apps
- [x] Create superuser
