### ISSUE TITLE
USER STORY : Setup Cloudinary for Media Storage and Deployment to Heroku MS1

### ISSUE THREAD

**Issue by hennasingh** [hennasingh/ArtisanAlley#3]
### **User Story**

As a developer, I want to deploy the application to Heroku early in development stage so that I can test the application as I continue developing it.

### **Priority**
[ X ] High
[ ] Medium
[ ] Low

### **Tasks**
- [x] Create a new app on Heroku
- [x] Install required packages (gunicorn, cloudinary) in the application for media storage and deployment
- [x] Update env.py file with Cloudinary API key and also add config  in django project settings file
- [x] Create requirements.txt file 
- [x] Create Procfile
- [x] Add Environment variables to Heroku and deploy 
- [x] Test the application
