### ISSUE TITLE
USER STORY : Setup Skeleton Templates and URLs for Path Routing MS1

### ISSUE THREAD

**Issue by hennasingh** [hennasingh/ArtisanAlley#4]
### **User Story**

As a developer, I want to add frontend logic and implement styles so that I can see the deployed UI when I route to the path.

### **Priority**
- [x] High
- [ ] Medium
- [ ] Low

### **Tasks**
- [x] Create separate urls.py file for apps and project
- [x] Create templates folder and add skeleton html files
- [x] Configure urlpatterns for both apps and project to render views on said routes
- [x] Add configuration in project settings.py to access template folder
- [x] Update views.py to render skeleton html files on defined routes
